"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['SkyEvent.py']
DATA_FILES = []
OPTIONS = {'iconfile': '/Users/nicholasrrichardson/Desktop/projects/SkyEvent/assets/happy_moon.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
